Populate Users
ymittal/codeu_project_2017 pull request #18
Opened 2017-04-23 04:58 UTC by corybrooks

This PR implements the feature to populate the current users and display their usernames in the Users fragment of the app.

2017-04-23 20:01 UTC, ymittal approved these changes
LGTM. Just remove extra line spacings in some files.

2017-04-23 20:19 UTC, blong1996 commented on android/app/src/main/java/com/google/codeu/chatme/view/adapter/UserListAdapter.java
> +        holder.tvName.setText(user.getName());
name has been changed to`fullName` and `username` in the  `User` model. merge the latest version of `dev` to this branch and make the necessary changes. I would suggest attempting to grab each user's Full Name first and, if empty, grab their username instead.

2017-04-23 20:29 UTC, blong1996 requested changes
pull latest changes from dev  branch and update references made to User objects in UserListAdapter, line 46

2017-04-24 23:54 UTC, ymittal approved these changes
LGTM.

2017-04-25 01:28 UTC, blong1996 approved these changes

2017-04-25 01:42 UTC, merged